/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.global.android.ContactBlackList;

public final class R {
    public static final class array {
        /**  Used in View/Spinner1.java 
 Used in View/Spinner1.java 
 Used in App/SearchInvoke.java 
 Used in app/dialog examples 
         */
        public static final int select_dialog_items=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int ic_menu_add=0x7f020001;
        public static final int icon=0x7f020002;
    }
    public static final class id {
        public static final int cancel_btn=0x7f06000f;
        public static final int ok_btn=0x7f06000e;
        public static final int phone_no__view=0x7f060002;
        public static final int phone_no_edit=0x7f060003;
        public static final int refuse_mms_no=0x7f06000d;
        public static final int refuse_mms_rg=0x7f06000b;
        public static final int refuse_mms_yes=0x7f06000c;
        public static final int refuse_phone_number=0x7f060005;
        public static final int refuse_phone_rb_no=0x7f060008;
        public static final int refuse_phone_rb_yes=0x7f060007;
        public static final int refuse_phone_rg=0x7f060006;
        public static final int table_row1=0x7f060004;
        public static final int table_row_mms=0x7f060009;
        public static final int tv_row_mms=0x7f06000a;
        public static final int username_edit=0x7f060001;
        public static final int username_view=0x7f060000;
        public static final int widget40=0x7f060010;
    }
    public static final class layout {
        public static final int alert_dialog_text_entry=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int add_black_list=0x7f05000d;
        public static final int alert_dialog_cancel=0x7f050006;
        public static final int alert_dialog_delect_phone_no=0x7f05000b;
        public static final int alert_dialog_eidt_phone_no=0x7f05000a;
        public static final int alert_dialog_ok=0x7f050005;
        public static final int alert_dialog_phone_no=0x7f050009;
        public static final int alert_dialog_text_entry=0x7f050007;
        public static final int alert_dialog_username=0x7f050008;
        public static final int alert_dialog_warning=0x7f05000f;
        public static final int all_number_will_delete=0x7f050011;
        public static final int app_name=0x7f050001;
        public static final int edit_black_list=0x7f05000e;
        public static final int menu_add_phone_no=0x7f050000;
        public static final int menu_del_phone_no=0x7f050002;
        public static final int menu_edit_phone_no=0x7f050003;
        public static final int menu_exit=0x7f050004;
        public static final int select_dialog=0x7f05000c;
        public static final int this_number_will_delete=0x7f050010;
    }
}
